version: '3'

services:
  
  authenza_db:
    image: postgres:12-alpine
    container_name: authenza_db
    volumes:
      - authenza_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  authenza_server:
    container_name: authenza_server
    build:
      context: .
      dockerfile: startup/server/Dockerfile-server
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL=${EMAIL_ID}
      - PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - authenza_db
  
  nginx_server:
    container_name: nginx_server
    build:
      context: .
      dockerfile: startup/nginx/Dockerfile-nginx
    ports:
      - 80:80
    environment:
      - API_KEY=${API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - BASE_URL=${BASE_URL}
    command: /bin/sh -c "/start.sh"
    depends_on:
      - authenza_server


volumes:
  authenza_data:
