FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./startup/nginx/nginx.conf /etc/nginx/conf.d/
COPY ./Web-Client /var/www/data
COPY /startup/nginx/start.sh /start.sh
RUN chmod +x /start.sh
